# Generated by Django 3.2.8 on 2021-11-20 22:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_first', models.CharField(max_length=20)),
                ('rep_last', models.CharField(max_length=20)),
                ('rep_email', models.EmailField(max_length=100)),
                ('rep_birth_date', models.DateField(default=datetime.datetime.today)),
                ('rep_believer', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_latitude', models.CharField(max_length=10)),
                ('sight_longitude', models.CharField(max_length=10)),
                ('Time_date', models.DateTimeField(default=datetime.datetime.today)),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=2)),
                ('Image', models.ImageField(upload_to='photos')),
                ('Description', models.TextField(max_length=5000)),
                ('reporter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squatchersapp.reporter')),
            ],
        ),
    ]
