# Generated by Django 3.2.8 on 2021-11-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squatchersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Image',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
