# Generated by Django 3.2.8 on 2021-12-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squatchersapp', '0003_sighting_sight_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='reporter_id',
            new_name='reporter',
        ),
    ]
