# Generated by Django 3.2.8 on 2021-12-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squatchersapp', '0004_rename_reporter_id_sighting_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='time_zone',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
