# Generated by Django 3.2.8 on 2021-12-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squatchersapp', '0005_sighting_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='sight_latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='sight_longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
