# Generated by Django 3.2.8 on 2021-12-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squatchersapp', '0007_auto_20211214_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='sight_date',
            field=models.DateField(default='2021-12-14'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='sight_time',
            field=models.TimeField(default='03:15'),
        ),
    ]
