# Generated by Django 3.2.8 on 2021-12-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squatchersapp', '0011_auto_20211214_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='sight_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='sight_time',
            field=models.TimeField(blank=True),
        ),
    ]
