# Generated by Django 3.2.8 on 2021-12-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squatchersapp', '0013_alter_sighting_sight_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='sight_date',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='sight_time',
        ),
        migrations.AddField(
            model_name='sighting',
            name='sight_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
