# Generated by Django 3.2.8 on 2021-12-14 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squatchersapp', '0014_auto_20211214_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='sight_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 3, 46, 23, 944014)),
        ),
    ]
