# Generated by Django 3.2.8 on 2021-12-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squatchersapp', '0019_alter_sighting_sight_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='sight_datetime',
        ),
    ]
