# Generated by Django 3.2.8 on 2021-12-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squatchersapp', '0021_sighting_sight_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='sight_datetime',
        ),
        migrations.AddField(
            model_name='sighting',
            name='sight_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
