# Generated by Django 3.2.8 on 2021-12-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squatchersapp', '0022_auto_20211214_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='sight_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
